-- Find Total Customers By Countries

SELECT
country,
COUNT(customer_key) AS total_customers
FROM  gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find Total Customers By Gender

SELECT
gender,
COUNT(customer_key) AS total_customers
FROM  gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find Total Products By Category

SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What Is The Average Costs In Each Category?

SELECT
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- What Is The Total Revenue Generated For Each Category?

SELECT
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find Total Revenue Is Generated By Each Customer

SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- What Is The Distribution Of Sold Items Across Countries?

SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC